"""端口层：只定义契约，不绑定具体实现。"""

from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable, Callable
from typing import Any, Protocol


class SessionStore(Protocol):
    async def get_or_create_session(self, user_id: str, conversation_id: str | None = None, shop_id: str | None = None) -> str: ...
    async def create_conversation(self, user_id: str, title: str = "新对话", shop_id: str | None = None) -> str: ...
    async def save_messages(self, session_id: str, messages: list[dict[str, Any]]) -> None: ...
    async def get_stage(self, session_id: str) -> str: ...
    async def update_stage(self, session_id: str, stage: str) -> None: ...
    async def get_session_shop_id(self, session_id: str) -> str | None: ...
    async def get_requirement(self, session_id: str): ...
    async def set_requirement(self, session_id: str, req: Any) -> None: ...
    async def get_long_term(self, user_id: str) -> dict[str, Any]: ...
    async def set_long_term(self, user_id: str, key: str, value: Any) -> None: ...
    async def get_session_json(self, user_id: str, session_id: str, key: str): ...
    async def set_session_json(self, user_id: str, session_id: str, key: str, value: Any) -> None: ...
    async def set_session_flag(self, user_id: str, session_id: str, key: str, value: str) -> None: ...
    async def get_session_flag(self, user_id: str, session_id: str, key: str) -> str | None: ...
    async def clear_session_flags(self, user_id: str, session_id: str, prefix: str = "") -> None: ...
    async def load_history(self, conversation_id: str, limit: int) -> list[dict[str, Any]]: ...


class PlanRepository(Protocol):
    async def get_plan(self, plan_id: str) -> dict[str, Any] | None: ...
    async def search_plans(self, keyword: str, requirement: Any | None = None, location: dict[str, float] | None = None) -> list[dict[str, Any]]: ...
    async def list_shop_plans(self, shop_id: str) -> list[dict[str, Any]]: ...


class ShopRepository(Protocol):
    async def get_shop(self, shop_id: str) -> dict[str, Any] | None: ...
    async def search_shops(self, requirement: Any | None = None, location: dict[str, float] | None = None, limit: int = 10) -> list[dict[str, Any]]: ...


class LLMProvider(Protocol):
    def chat(self, messages: list[dict[str, Any]], tools: list[dict[str, Any]] | None = None, stream: bool = False, response_format: dict[str, Any] | None = None, user_id: str | None = None) -> Any: ...
    def chat_stream(self, messages: list[dict[str, Any]], tools: list[dict[str, Any]] | None = None, user_id: str | None = None) -> Any: ...


class ImageProvider(Protocol):
    async def generate(self, prompt: str) -> str: ...


class KnowledgeBase(Protocol):
    def query(self, domain: str, query: str) -> list[dict[str, Any]]: ...
    def get_by_id(self, item_id: str) -> dict[str, Any] | None: ...


ToolHandler = Callable[[dict[str, Any] | None, dict[str, Any] | None], Awaitable[tuple[str, str]]]
